# Generated by Django 4.0.3 on 2022-03-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_alter_aluno_id_alter_curso_id_alter_matricula_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='fotos',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
